### ISSUE TITLE
Problem with Squeeze Server application

### ISSUE THREAD

**Issue by atrugiel69** [tool-maker/VPN_just_for_torrents#2]
For reasons that I completely fail to understand, the application in the title appears to try going on the internet through the VPN address, while failing to do so and not resolving internet addresses just the same.

To clarify, I would not care if it went through VPN or outside VPN but it should somehow go. I launch it without binding it in any way to the VPN virtual adapter, I don't launch it with ForceBindIP (but I tried using it to bind it on the regular ethernet adapter, to no avail).

Under Process Explorer I see that it uses the local address for port 3483 but it uses the VPN address for port 9000 (both are ports needed by Squeeze Server).
Process explorer lists:

Local address: VPN IP:9000 - Remote address: server:8676
Local address: VPN IP:9000 - Remote address: server:9812
Local address: VPN IP:9000 - Remote address: VPN IP:8652

Now I don't understand the implication of the ports used for remote addresses (maybe you do) but what I fail to understand is why the VPN IP enters the equation at all. Shouldn't it be completely transparent unless one specifically binds it through the application?
One thing I noticed is that without VPN (and batch files) I can call the web interface through 127.0.0.1:9000 whereas when the VPN is connected (and batch file has been used), it only responds to server:9000

When I write "VPN IP" I mean the address AirVPN actually uses, not the Exit IP.
In AirVPN lingo, it's "Your VPN IPv4" not "Exit IPv4".

"Your VPN IPv4" is what appears under "Interface IP" in the routing table.
There's an entry like this:

Destination: "Exit IPv4", Mask: 255.255.255.255, Gateway x.x.x.1 (where x is equal to the first three numbers of Your VPN IPv4"), Interface IP "Your VPN IPv4".

If you have a private address or something, I could send you the printout for the routing table. I'm just careful about not putting it here, in the open.

**Comment by tool-maker** [comment]
Does it work if you use the VPN without my scripts?

Either way, I think you will have to look to some sort of support forum for that server for help. I don't use it. Maybe it behaves badly in a multi-homed IP environment. It must be doing something it shouldn't.

**Comment by tool-maker** [comment]
ForceBindIP is only going to work in very simple situations. For example, if a program attempts to listen on 127.0.0.1, then ForceBindIP will interfere with that and force the bind to be to the external IP address. This may confuse or crash the program.
