### ISSUE TITLE
Are you available to chat sometime?

### ISSUE THREAD

**Issue by joe7dust** [tool-maker/VPN_just_for_torrents#3]
I dont usually run batch files that I don't fully understand and I feel like I could learn a lot by analyzing some weird issues I have after running this.

**Comment by tool-maker** [comment]
If you ask specific questions here with a bit more information, I will try to help (to a point). Then the discussion may be helpful to others too.

No private communication though. Sorry.

**Comment by joe7dust** [comment]
@tool-maker Sure, good idea. I was mainly curious how this could end up with partially working results. It seemed to me like something that would certainly be an all or nothing tweak. When my vpn is off I get some rubber banding in my online game that wasn't there before. It shouldn't affect the hops / route when the vpn is off I thought?

If it is not too much to ask, maybe you could add some notes to the first batch file every 5 lines or so? I would like to fully understand everything in it.

**Comment by tool-maker** [comment]
I have no idea what you mean by "rubber banding".

All the batch script does is ensure that the original default gateway remains the default gateway when the VPN is on. Any program that just uses the default gateway will not be affected.

Compare the routing table with the VPN up and with the VPN down to ensure that the VPN is not attempting to override the default gateway in a manner that is not the normal thing. What routing table entries does the VPN add?

Yes, the Windows batch file could use some comments. When I am in the mood and have some time perhaps I will add some.

**Comment by joe7dust** [comment]
> I have no idea what you mean by "rubber banding".
> 
> All the batch script does is ensure that the original default gateway remains the default gateway when the VPN is on. Any program that just uses the default gateway will not be affected.
> 
> Compare the routing table with the VPN up and with the VPN down to ensure that the VPN is not attempting to override the default gateway in a manner that is not the normal thing. What routing table entries does the VPN add?
> 
> Also, use Process Explorer to see what IP interfaces your game program binds to, both with the VPN up and off, in case it is doing something unusual.
> 
> ===
> 
> Yes, the Windows batch file could use some comments. When I am in the mood and have some time perhaps I will add some.

Rubber banding is when players seem to teleport/skip around unusually. Sometimes it is you getting yoinked back to a previous position by the server, but in my case I'll be looking at opponents and see them skipping about every second or so. It makes it very difficult to engage. It is usually caused by lag, but I guess having port settings that are incorrect might cause it to although usually that would yield more binary results.
